// CODEC-IMPORTS
import type { Operation, ParamKey } from './types';
// CODEC-IMPORTS-END
export const operations: Operation[] = [
  {
    id: 'smart-decode',
    category: 'smart',
    name: { zh: '智能多层解码', en: 'Smart Decode' },
    summary: { zh: '自动尝试 URL、HTML、Unicode、Base64、Hex 等常见嵌套编码，并优先停在看起来像明文的结果。', en: 'Automatically tries URL, HTML, Unicode, Base64, Hex, and common nested encodings.' },
    supportsEncode: false,
    decodeLabel: { zh: '智能解码', en: 'Smart decode' },
  },
  {
    id: 'url-component',
    category: 'web',
    name: { zh: 'URL 组件编码', en: 'URL Component' },
    summary: { zh: '对参数值、路径片段和 payload 片段做百分号编码或解码。', en: 'Percent-encode or decode parameter values, path fragments, and payload snippets.' },
  },
  {
    id: 'url-form',
    category: 'web',
    name: { zh: '表单 URL 编码', en: 'Form URL Encoding' },
    summary: { zh: '适合 `application/x-www-form-urlencoded` 场景，空格会编码为 `+`。', en: 'Encodes or decodes application/x-www-form-urlencoded data, where spaces become +.' },
  },
  {
    id: 'html-entity',
    category: 'web',
    name: { zh: 'HTML 实体', en: 'HTML Entity' },
    summary: { zh: '支持命名实体、十进制实体和十六进制实体三种输出形式。', en: 'Supports named, decimal, and hexadecimal HTML entity output.' },
    params: ['variant'],
  },
  {
    id: 'xml-entity',
    category: 'web',
    name: { zh: 'XML 实体', en: 'XML Entity' },
    summary: { zh: '适合 XML、SOAP、SAML 场景，支持命名实体、十进制和十六进制实体输出。', en: 'For XML, SOAP, and SAML payloads with named, decimal, and hexadecimal entity output.' },
    params: ['variant'],
  },
  {
    id: 'unicode-escape',
    category: 'web',
    name: { zh: 'Unicode / Hex 转义', en: 'Unicode / Hex Escape' },
    summary: { zh: '在普通文本与 \\uXXXX、\\u{XXXX}、\\xHH 风格转义之间互转。', en: 'Converts between \\uXXXX, \\u{XXXX}, \\xHH, and normal text.' },
    params: ['variant'],
  },
  {
    id: 'utf7',
    category: 'web',
    name: { zh: 'UTF-7', en: 'UTF-7' },
    summary: { zh: '在文本与 UTF-7 之间互转，适合旧邮件、编码兼容和 CTF Unicode 题。', en: 'Converts text to and from UTF-7 for legacy mail, web encoding bypass, and CTF Unicode puzzles.' },
  },
  {
    id: 'js-string',
    category: 'web',
    name: { zh: 'JavaScript 字符串', en: 'JavaScript String' },
    summary: { zh: '把文本转成 JavaScript 字符串字面量安全转义，也支持反向还原。', en: 'Escapes text for JavaScript string literals and reverses it.' },
  },
  {
    id: 'c-string',
    category: 'text',
    name: { zh: 'C / Python 转义', en: 'C / Python Escapes' },
    summary: { zh: '在普通文本与 \\n、\\xHH、\\ooo、\\uXXXX、\\UXXXXXXXX 风格转义之间互转，适合 shellcode、日志和源码片段', en: 'Converts text to and from \\n, \\xHH, \\ooo, \\uXXXX, and \\UXXXXXXXX escapes for shellcode, logs, and source snippets.' },
  },
  {
    id: 'json-string',
    category: 'text',
    name: { zh: 'JSON 字符串 / 格式化', en: 'JSON String / Pretty' },
    summary: { zh: '编码时生成 JSON 字符串；解码时自动反转义或格式化 JSON。', en: 'Encodes as a JSON string; decodes by unescaping or pretty-printing JSON.' },
  },
  {
    id: 'unix-time',
    category: 'text',
    name: { zh: 'Unix 时间', en: 'Unix Time' },
    summary: { zh: '在 ISO 时间、秒级 / 毫秒级 Unix 时间戳之间互转，适合日志、JWT 和 API 时间字段分析。', en: 'Converts between ISO datetimes and second/millisecond Unix timestamps for logs, JWTs, and APIs.' },
  },
  {
    id: 'base64',
    category: 'binary',
    name: { zh: 'Base64', en: 'Base64' },
    summary: { zh: '在 UTF-8 文本与标准 Base64 之间互转。', en: 'Converts UTF-8 text to and from standard Base64.' },
  },
  {
    id: 'base64url',
    category: 'binary',
    name: { zh: 'Base64URL', en: 'Base64URL' },
    summary: { zh: '适合 JWT、URL 参数和无填充 Base64 场景', en: 'Useful for JWTs, URL parameters, and unpadded Base64.' },
  },
  {
    id: 'base32',
    category: 'binary',
    name: { zh: 'Base32', en: 'Base32' },
    summary: { zh: 'RFC 4648 风格的 Base32，常见于密钥、令牌和各类编码题。', en: 'RFC 4648-style Base32 for keys, tokens, and CTF encodings.' },
    params: ['variant'],
  },
  {
    id: 'z-base-32',
    category: 'binary',
    name: { zh: 'z-base-32', en: 'z-base-32' },
    summary: { zh: 'Zimmermann 人类友好 Base32：小写字母表、无填充字符，Tahoe-LAFS 与 ZRTP 场景常见。', en: "Zimmermann's human-oriented Base32: lowercase unpadded alphabet, common in Tahoe-LAFS and ZRTP." },
  },
  {
    id: 'base45',
    category: 'binary',
    name: { zh: 'Base45', en: 'Base45' },
    summary: { zh: 'RFC 9285 Base45，常见于二维码、数字证书和紧凑文本传输场景。', en: 'RFC 9285 Base45 for QR-oriented and compact transfer scenarios.' },
  },
  {
    id: 'base58',
    category: 'binary',
    name: { zh: 'Base58', en: 'Base58' },
    summary: { zh: '使用 Bitcoin 字母表的 Base58，避开 0/O/I/l 等易混字符。', en: 'Bitcoin alphabet Base58 without confusing 0/O/I/l characters.' },
  },
  {
    id: 'base58check',
    category: 'binary',
    name: { zh: 'Base58Check', en: 'Base58Check' },
    summary: { zh: 'Bitcoin 风格 Base58Check，带版本字节和双 SHA-256 校验，适合地址、WIF 和钱包类题目。', en: 'Bitcoin-style Base58Check with version byte and double-SHA256 checksum for addresses, WIF keys, and wallet CTFs.' },
    params: ['versionHex'],
  },
  {
    id: 'bech32',
    category: 'binary',
    name: { zh: 'Bech32 / Bech32m', en: 'Bech32 / Bech32m' },
    summary: { zh: 'BIP173 / BIP350 地址编码，支持 HRP、Bech32 和 Bech32m 校验。', en: 'BIP173/BIP350 address encoding with HRP, Bech32, and Bech32m checksums for blockchain and forensic CTFs.' },
    params: ['variant', 'hrp'],
  },
  {
    id: 'base62',
    category: 'binary',
    name: { zh: 'Base62', en: 'Base62' },
    summary: { zh: '常见于短链、邀请码和压缩数字 ID 场景。', en: 'Common for short URLs, invite codes, and compact numeric IDs.' },
  },
  {
    id: 'base36',
    category: 'binary',
    name: { zh: 'Base36', en: 'Base36' },
    summary: { zh: '使用 0-9A-Z 字母表的进制编码，常见于短 ID、序列号和自定义进制提示。', en: '0-9A-Z radix encoding for CTF short IDs, serials, and custom-base hints.' },
  },
  {
    id: 'base91',
    category: 'binary',
    name: { zh: 'Base91', en: 'Base91' },
    summary: { zh: '高密度二进制转文本编码，常被当作 Base 家族的混淆层。', en: 'High-density binary-to-text encoding often used as a Base-family CTF obfuscation layer.' },
  },
  {
    id: 'base32768',
    category: 'binary',
    name: { zh: 'Base32768', en: 'Base32768' },
    summary: { zh: '每个字符承载 15 bit 的 Unicode 高密度编码，输出形似 CJK 生僻字，常用于超短载体题。', en: 'High-density Unicode encoding packing 15 bits per character; output looks like rare CJK glyphs.' },
  },
  {
    id: 'ascii85',
    category: 'binary',
    name: { zh: 'ASCII85 / Base85', en: 'ASCII85 / Base85' },
    summary: { zh: '适合 PostScript、PDF 和二进制转文本封装场景，支持 Adobe ASCII85 与 Z85。', en: 'Useful for PostScript, PDF, and binary-to-text wrappers with Adobe ASCII85 and Z85.' },
    params: ['variant'],
  },
  {
    id: 'uuencode',
    category: 'binary',
    name: { zh: 'UUencode', en: 'UUencode' },
    summary: { zh: '经典 Unix 邮件附件文本封装格式，CTF 杂项和取证题里仍会出现。', en: 'Legacy Unix mail attachment text wrapper that still appears in CTF misc and forensics tasks.' },
    params: ['blockLabel'],
  },
  {
    id: 'xxencode',
    category: 'binary',
    name: { zh: 'XXencode', en: 'XXencode' },
    summary: { zh: 'UUencode 的字母数字变体（+- 开头字母表），老邮件归档与 CTF 取证题仍会见到。', en: 'Alphanumeric UUencode variant with a +-leading alphabet, still seen in legacy mail archives and CTF forensics.' },
  },
  {
    id: 'hex',
    category: 'binary',
    name: { zh: 'Hex 十六进制', en: 'Hex' },
    summary: { zh: '支持纯 Hex、0x 前缀、\\x 前缀和空格分隔格式。', en: 'Supports plain hex, 0x prefixes, \\x prefixes, and spaced hex.' },
    params: ['variant'],
  },
  {
    id: 'binary',
    category: 'binary',
    name: { zh: '二进制字', en: 'Binary Bytes' },
    summary: { zh: '在文本与 8 位二进制字节串之间互转。', en: 'Converts text to and from 8-bit binary byte strings.' },
    params: ['separator'],
  },
  {
    id: 'octal-codes',
    category: 'binary',
    name: { zh: 'Octal / 八进', en: 'Octal Codes' },
    summary: { zh: '在文本与八进制字符码之间互转，支持 \\ooo、0o 前缀和空格分隔格式。', en: 'Converts text and octal character codes, including \\ooo, 0o-prefixed, and spaced CTF forms.' },
    params: ['separator'],
  },
  {
    id: 'ascii-codes',
    category: 'binary',
    name: { zh: 'ASCII / Decimal', en: 'ASCII / Decimal' },
    summary: { zh: '文本与十进制字符编码互转', en: 'Converts text to and from decimal character codes.' },
    params: ['separator'],
  },
  {
    id: 'a1z26',
    category: 'binary',
    name: { zh: 'A1Z26 字母数字', en: 'A1Z26' },
    summary: { zh: 'A=1 到 Z=26 的字母编号，常见于入门 CTF 编码题。', en: 'Maps A=1 through Z=26, a common beginner CTF encoding.' },
    params: ['separator'],
  },
  {
    id: 'morse',
    category: 'binary',
    name: { zh: 'Morse 摩斯', en: 'Morse Code' },
    summary: { zh: '英文、数字和常见符号与摩斯码互转', en: 'Converts letters, digits, and common symbols to and from Morse code.' },
  },
  {
    id: 'nato-phonetic',
    category: 'binary',
    name: { zh: 'NATO 音标字母', en: 'NATO Phonetic' },
    summary: { zh: '在字母与 Alpha / Bravo / Charlie 这类 NATO 音标词之间互转。', en: 'Converts letters to and from Alpha/Bravo/Charlie words used in radio, voice, and beginner CTF puzzles.' },
    params: ['separator'],
  },
  {
    id: 'baudot',
    category: 'binary',
    name: { zh: 'Baudot / ITA2', en: 'Baudot / ITA2' },
    summary: { zh: '5-bit Baudot / ITA2 电传码，自动处理字母态与数字符号态之间的移位控制。', en: '5-bit Baudot/ITA2 teleprinter code with automatic Letters/Figures shift handling.' },
    params: ['separator'],
  },
  {
    id: 'bcd',
    category: 'binary',
    name: { zh: 'BCD 二进制十进制', en: 'BCD' },
    summary: { zh: '在十进制数字与 4-bit BCD 半字节之间互转，适合硬件、取证和杂项题。', en: 'Converts decimal digits to and from 4-bit BCD nibbles for hardware, forensics, and misc CTF tasks.' },
    params: ['separator'],
  },
  {
    id: 'gray-code',
    category: 'binary',
    name: { zh: 'Gray Code 格雷', en: 'Gray Code' },
    summary: { zh: '在二进制或十进制整数与 Gray Code 之间互转；裸 0/1 串按二进制，支持 0b / 0d 前缀消除歧义。', en: 'Converts binary or decimal integers to and from Gray code; bare 0/1 strings are binary, with 0b/0d prefixes for unambiguous input.' },
    params: ['separator'],
  },
  {
    id: 'dna-code',
    category: 'binary',
    name: { zh: 'DNA 编码', en: 'DNA Encoding' },
    summary: { zh: '用 A / C / G / T 表示 2-bit 数据，适合 DNA 编码层分析。', en: 'Represents 2-bit data with A/C/G/T for common CTF DNA binary encoding layers.' },
    params: ['variant', 'separator'],
  },
  {
    id: 'gsm7',
    category: 'binary',
    name: { zh: 'GSM 7-bit', en: 'GSM 7-bit' },
    summary: { zh: '在 GSM 03.38 默认字母表文本与 7-bit 打包 Hex 之间互转。', en: 'Converts GSM 03.38 default alphabet text to and from 7-bit packed hex for SMS PDU, mobile forensics, and misc CTF tasks.' },
  },
  {
    id: 'sms-pdu',
    category: 'binary',
    name: { zh: 'SMS PDU 解析', en: 'SMS PDU Parser' },
    summary: { zh: '解析 GSM SMS-DELIVER / SUBMIT PDU，包括 SMSC、号码、时间戳、DCS 和用户数据。', en: 'Parses GSM SMS-DELIVER/SUBMIT PDU fields including SMSC, address, timestamp, DCS, and user data for mobile-forensics and misc CTF tasks.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 PDU', en: 'Parse PDU' },
  },
  {
    id: 'cbor',
    category: 'binary',
    name: { zh: 'CBOR 解析', en: 'CBOR Parser' },
    summary: { zh: '把 Hex / Base64 形式的 CBOR 解析为主要类型、Tag、数组、Map 和文本值。', en: 'Parses CBOR from Hex/Base64 into major types, tags, arrays, maps, byte strings, and text values.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 CBOR', en: 'Parse CBOR' },
  },
  {
    id: 'messagepack',
    category: 'binary',
    name: { zh: 'MessagePack 解析', en: 'MessagePack Parser' },
    summary: { zh: '解析 Hex / Base64 形式的 MessagePack，适合 API 抓包、缓存文件和二进制对象题。', en: 'Parses MessagePack from Hex/Base64 for API captures, cache files, and binary-object misc challenges.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 MsgPack', en: 'Parse MsgPack' },
  },
  {
    id: 'protobuf-raw',
    category: 'binary',
    name: { zh: 'Protobuf Wire 解析', en: 'Protobuf Wire Parser' },
    summary: { zh: '基于 protobufjs Reader 解析无 schema 的 Protobuf wire 字段，展示 field、wire type、varint 和 length-delimited 预览。', en: 'Uses protobufjs Reader to parse schema-less Protobuf wire fields, showing field numbers, wire types, varints, fixed values, and length-delimited previews.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 Protobuf', en: 'Parse Protobuf' },
  },
  {
    id: 'bson',
    category: 'binary',
    name: { zh: 'BSON 解析', en: 'BSON Parser' },
    summary: { zh: '使用官方 `bson` 包把 MongoDB BSON 文档解析成 Extended JSON，适合导出、缓存和取证数据。', en: 'Uses the official bson package to parse MongoDB BSON documents into Extended JSON for database dumps, caches, and forensics challenges.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 BSON', en: 'Parse BSON' },
  },
  {
    id: 'yenc',
    category: 'binary',
    name: { zh: 'yEnc', en: 'yEnc' },
    summary: { zh: '在文本与 yEnc 转义流之间互转，适合旧格式附件和取证题。', en: 'Converts text to and from yEnc escaped streams used in newsgroup attachments, forensics, and legacy-format puzzles.' },
  },
  {
    id: 'bubble-babble',
    category: 'binary',
    name: { zh: 'Bubble Babble', en: 'Bubble Babble' },
    summary: { zh: '在 UTF-8 文本与 xigak-... 风格的 Bubble Babble 形式之间互转。', en: 'Converts UTF-8 text to and from the xigak-... Bubble Babble form often seen in OpenSSH fingerprints.' },
  },
  {
    id: 'quoted-printable',
    category: 'text',
    name: { zh: 'Quoted-Printable', en: 'Quoted-Printable' },
    summary: { zh: '邮件 MIME 中常见的编码格式，适合处理 =XX 转义和软换行。', en: 'Common MIME mail encoding for =XX escapes and soft line breaks.' },
  },
  {
    id: 'utf16-bytes',
    category: 'text',
    name: { zh: 'UTF-16 字节', en: 'UTF-16 Bytes' },
    summary: { zh: '在文本与 UTF-16 LE / BE 的十六进制字节序列之间互转。', en: 'Converts text to and from UTF-16 LE/BE hexadecimal byte sequences.' },
    params: ['variant', 'separator'],
  },
  {
    id: 'reverse-text',
    category: 'text',
    name: { zh: '反转 / 倒序', en: 'Reverse Text' },
    summary: { zh: '把文本整体倒序，适合反写 flag、镜像提示和简单倒序混淆。', en: 'Reverses text for backwards flags, reversed payloads, and simple mirror hints.' },
  },
  {
    id: 'keyboard-shift',
    category: 'text',
    name: { zh: '键盘偏移', en: 'Keyboard Shift' },
    summary: { zh: '还原左右偏移的 QWERTY 键盘误位输入，常见于杂项题和手工输入混淆。', en: 'Restores left/right QWERTY keyboard-shifted text common in CTF misc puzzles.' },
    params: ['variant'],
  },
  {
    id: 'zero-width',
    category: 'text',
    name: { zh: '零宽字符隐写', en: 'Zero-Width Stego' },
    summary: { zh: '用零宽字符隐藏或提取 UTF-8 文本，适合不可见字符隐写和文本混淆题。', en: 'Hides or extracts UTF-8 text using zero-width characters for invisible-character CTF puzzles.' },
  },
  {
    id: 'hash',
    category: 'crypto',
    name: { zh: 'Hash / Checksum', en: 'Hash / Checksum' },
    summary: { zh: '生成 MD5、SHA、CRC 等摘要或校验值；摘要本身不可逆。', en: 'Generates MD5, SHA, and CRC32 digests. Hashes are one-way.' },
    supportsDecode: false,
    encodeLabel: { zh: '生成摘要', en: 'Generate hash' },
    params: ['hashAlgorithm'],
  },
  {
    id: 'hash-identify',
    category: 'crypto',
    name: { zh: 'Hash 识别', en: 'Hash Identifier' },
    summary: { zh: '按长度和字符特征识别常见 MD5、SHA、NTLM、bcrypt、Argon2、CRC 等摘要格式。', en: 'Identifies common MD5, SHA, NTLM, bcrypt, Argon2, CRC, and related hash formats by shape.' },
    supportsEncode: false,
    decodeLabel: { zh: '识别格式', en: 'Identify' },
  },
  {
    id: 'hmac',
    category: 'crypto',
    name: { zh: 'HMAC', en: 'HMAC' },
    summary: { zh: '使用密钥生成 HMAC 摘要，适合接口签名校验和 token 完整性验证。', en: 'Generates HMAC-SHA digests with a secret key for API signatures.' },
    supportsDecode: false,
    encodeLabel: { zh: '生成 HMAC', en: 'Generate HMAC' },
    params: ['hashAlgorithm', 'secret'],
  },
  {
    id: 'bip39-seed',
    category: 'crypto',
    name: { zh: 'BIP39 助记词 Seed', en: 'BIP39 Mnemonic Seed' },
    summary: { zh: '按 BIP39 规范使用 PBKDF2-HMAC-SHA512，从助记词和可选 passphrase 派生 512-bit seed。', en: 'Derives the 512-bit BIP39 seed from a mnemonic and optional passphrase using PBKDF2-HMAC-SHA512 for wallet and seed-recovery challenges.' },
    supportsEncode: false,
    decodeLabel: { zh: '派生 Seed', en: 'Derive seed' },
    params: ['secret'],
  },
  {
    id: 'aes-gcm',
    category: 'crypto',
    name: { zh: 'AES-GCM', en: 'AES-GCM' },
    summary: { zh: '基于口令的 AES-GCM 加密/解密，输出包含 salt、IV 和 ciphertext 的 JSON 结构。', en: 'Password-based AES-GCM encryption/decryption with JSON salt, IV, and ciphertext output.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iterations'],
  },
  {
    id: 'aes-cbc',
    category: 'crypto',
    name: { zh: 'AES-CBC', en: 'AES-CBC' },
    summary: { zh: '基于口令派生 256-bit AES-CBC，输出包含 salt、IV 和 ciphertext 的 JSON 结构。', en: 'Password-derived 256-bit AES-CBC with JSON salt, IV, and ciphertext output.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iterations'],
  },
  {
    id: 'aes-ctr',
    category: 'crypto',
    name: { zh: 'AES-CTR', en: 'AES-CTR' },
    summary: { zh: '基于口令派生 AES-CTR，适合验证流模式、nonce 复用和已知明文分析。', en: 'Password-derived AES-CTR for validating stream-mode, nonce reuse, and known-plaintext analysis.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iterations'],
  },
  {
    id: 'openssl-aes-256-cbc',
    category: 'crypto',
    name: { zh: 'OpenSSL enc AES-256-CBC', en: 'OpenSSL enc AES-256-CBC' },
    summary: { zh: '兼容经典 `openssl enc` 的 `Salted__` / `U2FsdGVkX1` 格式，使用 MD5 `EVP_BytesToKey` 派生 key / IV。', en: 'Compatible with the classic openssl enc Salted__ / U2FsdGVkX1 format and MD5 EVP_BytesToKey derivation.' },
    encodeLabel: { zh: 'OpenSSL 加密', en: 'OpenSSL encrypt' },
    decodeLabel: { zh: 'OpenSSL 解密', en: 'OpenSSL decrypt' },
    params: ['secret'],
  },
  {
    id: 'aes-cbc-raw',
    category: 'crypto',
    name: { zh: 'AES-CBC Raw', en: 'AES-CBC Raw' },
    summary: { zh: '原始密钥 AES-CBC，使用 16-byte IV，支持 PKCS#7 padding 或精确分组无 padding 模式。', en: 'Raw-key AES-CBC with a 16-byte IV, supporting PKCS#7 padding or exact-block no-padding CTF data.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['variant', 'secret', 'iv'],
  },
  {
    id: 'aes-ctr-raw',
    category: 'crypto',
    name: { zh: 'AES-CTR Raw', en: 'AES-CTR Raw' },
    summary: { zh: '原始密钥 AES-CTR，使用 16-byte counter block，适合流模式密文还原和 nonce 复用检查。', en: 'Raw-key AES-CTR with a 16-byte counter block for stream-mode ciphertext recovery and nonce-reuse checks.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'aes-ofb',
    category: 'crypto',
    name: { zh: 'AES-OFB', en: 'AES-OFB' },
    summary: { zh: '原始密钥 AES-OFB，使用 16-byte IV，适合旧式流模式 AES 数据。', en: 'Raw-key AES-OFB with a 16-byte IV for legacy stream-style AES challenges.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'aes-ecb',
    category: 'crypto',
    name: { zh: 'AES-ECB', en: 'AES-ECB' },
    summary: { zh: '原始密钥 AES-ECB，支持 PKCS#7 padding 或精确分组无 padding 模式。', en: 'Raw-key AES-ECB with PKCS#7 padding or exact-block no-padding mode for basic CTF crypto tasks.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['variant', 'secret'],
  },
  {
    id: 'aes-cfb',
    category: 'crypto',
    name: { zh: 'AES-CFB', en: 'AES-CFB' },
    summary: { zh: '原始密钥 AES-CFB-128，使用 16-byte IV，适合反馈模式密文还原。', en: 'Raw-key AES-CFB-128 with a 16-byte IV for feedback-mode ciphertext recovery.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'aes-kw',
    category: 'crypto',
    name: { zh: 'AES-KW', en: 'AES-KW' },
    summary: { zh: 'RFC 3394 AES Key Wrap，用 KEK 包裹或解包至少 16 字节且按 8 字节对齐的密钥材料。', en: 'RFC 3394 AES Key Wrap for wrapping or unwrapping 8-byte-aligned key material of at least 16 bytes with a KEK.' },
    encodeLabel: { zh: '包裹密钥', en: 'Wrap key' },
    decodeLabel: { zh: '解包密钥', en: 'Unwrap key' },
    params: ['secret'],
  },
  {
    id: 'aes-kwp',
    category: 'crypto',
    name: { zh: 'AES-KWP', en: 'AES-KWP' },
    summary: { zh: 'RFC 5649 的 AES Key Wrap with Padding，适合较短或非 8 字节对齐的 key blob。', en: 'RFC 5649 AES Key Wrap with Padding for short or non-8-byte-aligned key blobs.' },
    encodeLabel: { zh: '包裹密钥', en: 'Wrap key' },
    decodeLabel: { zh: '解包密钥', en: 'Unwrap key' },
    params: ['secret'],
  },
  {
    id: 'aes-cmac',
    category: 'crypto',
    name: { zh: 'AES-CMAC', en: 'AES-CMAC' },
    summary: { zh: 'RFC 4493 AES-CMAC，输出 16-byte tag，适合协议 MAC 和固件校验题。', en: 'RFC 4493 AES-CMAC producing a 16-byte tag for protocol MACs and firmware verification tasks.' },
    encodeLabel: { zh: '计算 CMAC', en: 'Compute CMAC' },
    supportsDecode: false,
    params: ['secret'],
  },
  {
    id: 'aes-gcm-siv',
    category: 'crypto',
    name: { zh: 'AES-GCM-SIV', en: 'AES-GCM-SIV' },
    summary: { zh: 'RFC 8452 的 nonce-misuse-resistant AEAD，使用 12-byte nonce，并支持可选 AAD。', en: 'RFC 8452 nonce-misuse-resistant AEAD with a 12-byte nonce and optional AAD.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv', 'associatedData'],
  },
  {
    id: 'aes-siv',
    category: 'crypto',
    name: { zh: 'AES-SIV', en: 'AES-SIV' },
    summary: { zh: 'RFC 5297 Synthetic IV AEAD；留空 nonce 时为确定性模式，填写时会作为最终 AAD 组件。', en: 'RFC 5297 Synthetic IV AEAD; leave nonce empty for deterministic SIV or provide it as the final AAD component.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv', 'associatedData'],
  },
  {
    id: 'des',
    category: 'crypto',
    name: { zh: 'DES', en: 'DES' },
    summary: { zh: '支持 DES-CBC / ECB 和 OpenSSL Salted__ passphrase 格式，适合旧协议和基础密码题。', en: 'DES-CBC/ECB plus OpenSSL Salted__ passphrase format for legacy protocols, weak crypto, and CTF basics.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['variant', 'secret', 'iv'],
  },
  {
    id: 'triple-des',
    category: 'crypto',
    name: { zh: 'TripleDES / 3DES', en: 'TripleDES / 3DES' },
    summary: { zh: '支持 3DES-CBC / ECB 和 OpenSSL Salted__ passphrase 格式，适合旧系统和 DESede 数据。', en: '3DES-CBC/ECB plus OpenSSL Salted__ passphrase format for legacy systems and DESede-style CTF data.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['variant', 'secret', 'iv'],
  },
  {
    id: 'blowfish',
    category: 'crypto',
    name: { zh: 'Blowfish', en: 'Blowfish' },
    summary: { zh: '支持 Blowfish-CBC / ECB 和 OpenSSL Salted__ passphrase 格式，适合旧应用和取证样本。', en: 'Blowfish-CBC/ECB plus OpenSSL Salted__ passphrase format for legacy apps, forensics samples, and CTF symmetric crypto.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['variant', 'secret', 'iv'],
  },
  {
    id: 'rabbit',
    category: 'crypto',
    name: { zh: 'Rabbit', en: 'Rabbit' },
    summary: { zh: 'Rabbit 流密码，兼容 OpenSSL Salted__ passphrase 格式，适合旧式流密码数据。', en: 'Rabbit stream cipher plus OpenSSL Salted__ passphrase format for CyberChef and CTF legacy stream-cipher data.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['variant', 'secret', 'iv'],
  },
  {
    id: 'chacha20-orig',
    category: 'crypto',
    name: { zh: 'ChaCha20 原始版', en: 'ChaCha20 Original' },
    summary: { zh: '原始 ChaCha20 XOR 流密码，使用 32-byte key 和 8-byte nonce，兼容 PyCryptodome ChaCha20。', en: 'Original ChaCha20 XOR stream cipher with a 32-byte key and 8-byte nonce, compatible with PyCryptodome ChaCha20.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'chacha20',
    category: 'crypto',
    name: { zh: 'ChaCha20', en: 'ChaCha20' },
    summary: { zh: 'RFC 8439 的 ChaCha20 XOR 流密码，使用 32-byte key 和 12-byte nonce。', en: 'RFC 8439 ChaCha20 XOR stream cipher with a 32-byte key and 12-byte nonce.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'xchacha20',
    category: 'crypto',
    name: { zh: 'XChaCha20', en: 'XChaCha20' },
    summary: { zh: 'XChaCha20 扩展 nonce 变体，使用 32-byte key 和 24-byte nonce，常见于 libsodium 数据。', en: 'XChaCha20 extended-nonce variant with a 32-byte key and 24-byte nonce, commonly seen in libsodium data.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'chacha20-poly1305',
    category: 'crypto',
    name: { zh: 'ChaCha20-Poly1305', en: 'ChaCha20-Poly1305' },
    summary: { zh: 'RFC 8439 的 AEAD 实现，使用 32-byte key、12-byte nonce 和 16-byte tag，支持可选 AAD。', en: 'RFC 8439 AEAD with a 32-byte key, 12-byte nonce, 16-byte tag, and optional AAD.' },
    encodeLabel: { zh: '加密并认证', en: 'Encrypt + authenticate' },
    decodeLabel: { zh: '验证并解密', en: 'Verify + decrypt' },
    params: ['secret', 'iv', 'associatedData'],
  },
  {
    id: 'xchacha20-poly1305',
    category: 'crypto',
    name: { zh: 'XChaCha20-Poly1305', en: 'XChaCha20-Poly1305' },
    summary: { zh: '扩展 nonce 的 AEAD，使用 32-byte key、24-byte nonce 和 16-byte tag，常见于 libsodium 抓包。', en: 'Extended-nonce AEAD with a 32-byte key, 24-byte nonce, 16-byte tag, and optional AAD.' },
    encodeLabel: { zh: '加密并认证', en: 'Encrypt + authenticate' },
    decodeLabel: { zh: '验证并解密', en: 'Verify + decrypt' },
    params: ['secret', 'iv', 'associatedData'],
  },
  {
    id: 'salsa20',
    category: 'crypto',
    name: { zh: 'Salsa20', en: 'Salsa20' },
    summary: { zh: 'Salsa20 XOR 流密码，支持 16 / 32-byte key 和 8-byte nonce，适合旧式流密码场景。', en: 'Salsa20 XOR stream cipher with 16/32-byte keys and an 8-byte nonce for legacy and stream-cipher basics.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'xsalsa20',
    category: 'crypto',
    name: { zh: 'XSalsa20', en: 'XSalsa20' },
    summary: { zh: 'XSalsa20 扩展 nonce 变体，使用 32-byte key 和 24-byte nonce，常见于 NaCl secretbox 相关数据。', en: 'XSalsa20 extended-nonce variant with a 32-byte key and 24-byte nonce, common in NaCl secretbox-related tasks.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'xsalsa20-poly1305',
    category: 'crypto',
    name: { zh: 'XSalsa20-Poly1305 / secretbox', en: 'XSalsa20-Poly1305 / secretbox' },
    summary: { zh: '兼容 NaCl / libsodium `secretbox` 的 AEAD，使用 32-byte key、24-byte nonce 和 16-byte tag。', en: 'NaCl/libsodium secretbox-compatible AEAD with a 32-byte key, 24-byte nonce, and 16-byte tag.' },
    encodeLabel: { zh: '加密并认证', en: 'Encrypt + authenticate' },
    decodeLabel: { zh: '验证并解密', en: 'Verify + decrypt' },
    params: ['secret', 'iv'],
  },
  {
    id: 'sm4',
    category: 'crypto',
    name: { zh: 'SM4', en: 'SM4' },
    summary: { zh: '国密 SM4 分组密码，支持 ECB / CBC 和 Hex 密文，适合国密协议与取证样本。', en: 'Chinese SM4 block cipher with ECB/CBC and hex ciphertext for GM/T protocol, forensic sample, and CTF crypto tasks.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['variant', 'secret', 'iv'],
  },
  {
    id: 'rc4',
    category: 'crypto',
    name: { zh: 'RC4', en: 'RC4' },
    summary: { zh: '经典流密码，适合旧协议、弱加密流量和基础流密码题。', en: 'Classic stream cipher for learning legacy protocol and weak-crypto traffic structures.' },
    params: ['secret'],
  },
  {
    id: 'rc4-drop',
    category: 'crypto',
    name: { zh: 'RC4-drop', en: 'RC4-drop' },
    summary: { zh: '丢弃前期 keystream 的 RC4 变体，适合旧协议复现和流密码检查。', en: 'RC4 variant that drops early keystream bytes for legacy protocol reproduction and CTF stream-cipher checks.' },
    params: ['secret', 'dropBytes'],
  },
  {
    id: 'tea',
    category: 'crypto',
    name: { zh: 'TEA', en: 'TEA' },
    summary: { zh: 'Tiny Encryption Algorithm，常见于逆向和混合密码题；使用 16-byte key，密文输入输出为 Hex。', en: 'Tiny Encryption Algorithm, common in reverse and mixed crypto CTFs; hex ciphertext output/input with a 16-byte key.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret'],
  },
  {
    id: 'xtea',
    category: 'crypto',
    name: { zh: 'XTEA', en: 'XTEA' },
    summary: { zh: '改进版 TEA，使用 64-bit 分组和 128-bit 密钥，常见于轻量加密与逆向题。', en: 'Improved TEA with 64-bit blocks and a 128-bit key, common in lightweight crypto and reversing challenges.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret'],
  },
  {
    id: 'xxtea',
    category: 'crypto',
    name: { zh: 'XXTEA', en: 'XXTEA' },
    summary: { zh: 'Corrected Block TEA，支持可变长度块，常见于移动端和逆向题。', en: 'Corrected Block TEA with variable-length blocks, often seen in mobile and CTF reversing tasks.' },
    encodeLabel: { zh: '加密', en: 'Encrypt' },
    decodeLabel: { zh: '解密', en: 'Decrypt' },
    params: ['secret'],
  },
  {
    id: 'vigenere',
    category: 'crypto',
    name: { zh: 'Vigenere', en: 'Vigenere' },
    summary: { zh: '经典多表替换密码，适合 CTF、密码学入门和手工分析。', en: 'Classical polyalphabetic cipher for CTFs, crypto fundamentals, and manual analysis practice.' },
    params: ['secret'],
  },
  {
    id: 'beaufort',
    category: 'crypto',
    name: { zh: 'Beaufort', en: 'Beaufort' },
    summary: { zh: '与 Vigenere 接近，但公式为 key - plaintext，编码和解码互逆。', en: 'Vigenere-like cipher using key - plaintext; encryption and decryption are reciprocal.' },
    params: ['secret'],
  },
  {
    id: 'autokey',
    category: 'crypto',
    name: { zh: 'Autokey Vigenere', en: 'Autokey Vigenere' },
    summary: { zh: '把明文追加到密钥后的 Vigenere 变体，常用来绕开普通频率分析。', en: 'Vigenere variant that appends plaintext to the key, often used to evade basic frequency checks.' },
    params: ['secret'],
  },
  {
    id: 'atbash',
    category: 'crypto',
    name: { zh: 'Atbash', en: 'Atbash' },
    summary: { zh: 'A/Z、B/Y 对称替换，编码和解码相同', en: 'Mirrors A/Z and B/Y; encoding and decoding are identical.' },
  },
  {
    id: 'bacon',
    category: 'crypto',
    name: { zh: 'Bacon 培根密码', en: 'Bacon Cipher' },
    summary: { zh: '五位 A / B 分组古典密码，也支持 a/b 或 0/1 风格输入。', en: 'Five-symbol A/B classical cipher with a/b or 0/1 style input.' },
    params: ['separator'],
  },
  {
    id: 'polybius',
    category: 'crypto',
    name: { zh: 'Polybius 方阵', en: 'Polybius Square' },
    summary: { zh: '5x5 坐标方阵，I/J 合并，常见为 11 12 13 形式', en: '5x5 coordinate square with I/J merged, often seen as 11 12 13 pairs.' },
    params: ['separator'],
  },
  {
    id: 'tap-code',
    category: 'crypto',
    name: { zh: 'Tap Code 敲击', en: 'Tap Code' },
    summary: { zh: 'Polybius 风格敲击分组，支持数字坐标或点号坐标输入。', en: 'Polybius-style tap groups with numeric or dotted coordinate input.' },
    params: ['separator'],
  },
  {
    id: 'playfair',
    category: 'crypto',
    name: { zh: 'Playfair 双字', en: 'Playfair Cipher' },
    summary: { zh: '5x5 密钥方阵双字母替换，I/J 合并，并自动处理重复字母填充。', en: '5x5 keyed digraph substitution with I/J merged and automatic repeated-letter padding.' },
    params: ['secret'],
  },
  {
    id: 'hill2',
    category: 'crypto',
    name: { zh: 'Hill 2x2', en: 'Hill 2x2' },
    summary: { zh: '2x2 矩阵 Hill 密码，密钥支持 4 个数字或 4 个字母。', en: '2x2 matrix Hill cipher; key accepts four numbers or four letters.' },
    params: ['secret'],
  },
  {
    id: 'substitution',
    category: 'crypto',
    name: { zh: '单表替换', en: 'Monoalphabetic Substitution' },
    summary: { zh: '按 26 字母替换表做单表替换，适合验证频率分析结果。', en: 'Applies a 26-letter substitution alphabet for checking frequency-analysis results.' },
    params: ['secret'],
  },
  {
    id: 'affine',
    category: 'crypto',
    name: { zh: 'Affine 仿射密码', en: 'Affine Cipher' },
    summary: { zh: '仿射密码 E(x)=(a*x+b) mod 26，适合古典密码枚举和手工检查。', en: 'E(x)=(a*x+b) mod 26 for classical-cipher enumeration and manual checks.' },
    params: ['affineA', 'affineB'],
  },
  {
    id: 'rail-fence',
    category: 'crypto',
    name: { zh: 'Rail Fence 栅栏', en: 'Rail Fence' },
    summary: { zh: '按轨道数做栅栏换位，支持常见 rail fence 编码/解码', en: 'Rail-fence transposition by rail count with encode/decode support.' },
    params: ['rails'],
  },
  {
    id: 'scytale',
    category: 'crypto',
    name: { zh: 'Scytale 换位', en: 'Scytale' },
    summary: { zh: '按列数进行古典换位，适合 rail / columnar 类变体。', en: 'Classical transposition by column count for rail and columnar variants.' },
    params: ['rails'],
  },
  {
    id: 'columnar',
    category: 'crypto',
    name: { zh: 'Columnar 列换', en: 'Columnar Transposition' },
    summary: { zh: '按关键词排序列的换位密码，适合古典换位题检查。', en: 'Keyword-ordered column transposition for CTF classical transposition checks.' },
    params: ['secret'],
  },
  {
    id: 'porta',
    category: 'crypto',
    name: { zh: 'Porta 密码', en: 'Porta Cipher' },
    summary: { zh: '互逆型多表替换的 Porta 密码，适合 Vigenere 变体题检查。', en: 'Reciprocal polyalphabetic Porta cipher for Vigenere-variant checks.' },
    params: ['secret'],
  },
  {
    id: 'gronsfeld',
    category: 'crypto',
    name: { zh: 'Gronsfeld 密码', en: 'Gronsfeld Cipher' },
    summary: { zh: '数字密钥版 Vigenere，常由 PIN、序列号等提示触发。', en: 'Numeric-key Vigenere variant often hinted by PINs or serials.' },
    params: ['secret'],
  },
  {
    id: 'bifid',
    category: 'crypto',
    name: { zh: 'Bifid 双分密码', en: 'Bifid Cipher' },
    summary: { zh: 'Polybius 坐标分组再重排的古典密码，支持 period 参数。', en: 'Polybius coordinate fractionation cipher with configurable period.' },
    params: ['secret', 'period'],
  },
  {
    id: 'trifid',
    category: 'crypto',
    name: { zh: 'Trifid 三分密码', en: 'Trifid Cipher' },
    summary: { zh: '3x3x3 分组坐标密码，适合 27 字符方阵或立方体类古典谜题。', en: '3x3x3 fractionation cipher for 27-symbol classical puzzle grids.' },
    params: ['secret', 'period'],
  },
  {
    id: 'four-square',
    category: 'crypto',
    name: { zh: 'Four-Square 密码', en: 'Four-Square Cipher' },
    summary: { zh: '四方格双字母替换，需要两个关键词方阵', en: 'Digraph substitution using two keyed Polybius squares.' },
    params: ['secret', 'keyword2'],
  },
  {
    id: 'nihilist',
    category: 'crypto',
    name: { zh: 'Nihilist 密码', en: 'Nihilist Cipher' },
    summary: { zh: 'Polybius 数值与关键词数值相加，常见输出为数字组', en: 'Adds Polybius plaintext and keyword numbers, commonly emitted as numeric groups.' },
    params: ['secret', 'separator'],
  },
  {
    id: 'adfgx',
    category: 'crypto',
    name: { zh: 'ADFGX', en: 'ADFGX' },
    summary: { zh: 'Polybius 替换加列换位，一战时期密码，字符集为 ADFGX', en: 'WWI substitution plus columnar transposition using the ADFGX alphabet.' },
    params: ['secret', 'keyword2'],
  },
  {
    id: 'adfgvx',
    category: 'crypto',
    name: { zh: 'ADFGVX', en: 'ADFGVX' },
    summary: { zh: 'ADFGX 的 6x6 变体，同时支持字母和数字。', en: '6x6 ADFGX variant supporting letters and digits.' },
    params: ['secret', 'keyword2'],
  },
  {
    id: 'xor',
    category: 'crypto',
    name: { zh: 'XOR', en: 'XOR' },
    summary: { zh: '文本与密钥异或，编码输出 hex，解码从 hex 还原', en: 'XORs text with a key; encoding outputs hex and decoding restores text from hex.' },
    params: ['secret'],
  },
  {
    id: 'xor-bruteforce',
    category: 'crypto',
    name: { zh: '单字节 XOR 爆破', en: 'Single-byte XOR Brute Force' },
    summary: { zh: '对 Hex 密文尝试 0x00-0xff，并按可读性和 flag 特征给候选排序。', en: 'Tries 0x00-0xff over hex ciphertext and ranks candidates by readability/flag scoring.' },
    supportsEncode: false,
    decodeLabel: { zh: 'Brute force', en: 'Brute force' },
  },
  {
    id: 'xor-known-plaintext',
    category: 'crypto',
    name: { zh: 'XOR 已知明文求密', en: 'XOR Known Plaintext' },
    summary: { zh: '从 Hex 密文和已知明文片段中推导 keystream / key 片段，适合 flag{、PNG、ZIP 头。', en: 'Derives keystream/key fragments from hex ciphertext and known plaintext such as flag{, PNG, or ZIP headers.' },
    supportsEncode: false,
    decodeLabel: { zh: '推导密钥', en: 'Derive key' },
    params: ['knownPlaintext'],
  },
  {
    id: 'magic-xor-helper',
    category: 'crypto',
    name: { zh: '文件头 XOR 推钥', en: 'Magic-header XOR Helper' },
    summary: { zh: '从 Hex 密文与常见文件头签名中推导重复 XOR key 前缀。', en: 'Derives repeating XOR key prefixes from hex ciphertext and common file signatures.' },
    supportsEncode: false,
    decodeLabel: { zh: 'Derive candidates', en: 'Derive candidates' },
    params: ['knownPlaintext'],
  },
  {
    id: 'rot',
    category: 'crypto',
    name: { zh: 'ROT / Caesar', en: 'ROT / Caesar' },
    summary: { zh: '支持 ROT13、Caesar 位移和 ROT47。', en: 'Supports ROT13, Caesar shifts, and ROT47.' },
    params: ['variant', 'shift'],
  },
  {
    id: 'rot-bruteforce',
    category: 'crypto',
    name: { zh: 'ROT / Caesar 全枚', en: 'ROT / Caesar Brute Force' },
    summary: { zh: '一次列出 ROT1-25 和 ROT47，适合快速扫 Caesar 变体。', en: 'Lists ROT1-25 and ROT47 at once for quick Caesar-variant triage.' },
    supportsEncode: false,
    decodeLabel: { zh: '全枚', en: 'Enumerate' },
  },
  {
    id: 'rot8000',
    category: 'crypto',
    name: { zh: 'ROT8000', en: 'ROT8000' },
    summary: { zh: '对 BMP 字符做 0x8000 位移，适合高位 Unicode 混淆场景。', en: 'Applies a 0x8000 Unicode ROT over BMP characters for high-plane Unicode obfuscation in CTFs.' },
  },
  {
    id: 'enigma',
    category: 'crypto',
    name: { zh: 'Enigma I 转子', en: 'Enigma I Rotor Machine' },
    summary: { zh: '三转子 Enigma I 模拟器，支持 rotor、reflector、ring、position 和 plugboard 等完整设置。', en: 'Three-rotor Enigma I simulator with rotor, reflector, ring, position, and plugboard settings.' },
    encodeLabel: { zh: 'Enigma 变换', en: 'Enigma transform' },
    decodeLabel: { zh: 'Enigma 变换', en: 'Enigma transform' },
    params: ['secret'],
  },
  {
    id: 'rsa-raw',
    category: 'crypto',
    name: { zh: 'RSA Raw / Textbook', en: 'RSA Raw / Textbook' },
    summary: { zh: '基于 BigInt 的 textbook RSA 加解密；支持 n/e/d/p/q/phi/c/m，适合小明文、已分解 n 和无填充题。', en: 'Textbook RSA BigInt encrypt/decrypt from n/e/d/p/q/phi/c/m for CTF small-message, factored-n, and no-padding RSA tasks.' },
    encodeLabel: { zh: 'Encrypt m', en: 'Encrypt m' },
    decodeLabel: { zh: 'Decrypt c', en: 'Decrypt c' },
  },
  {
    id: 'rabin-raw',
    category: 'crypto',
    name: { zh: 'Rabin Raw', en: 'Rabin Raw' },
    summary: { zh: '基于 BigInt 的 Rabin 原始加解密；支持 n/p/q/c/m，解密时给出 CRT 合成后的 4 个候选明文。', en: 'BigInt Rabin raw encrypt/decrypt from n/p/q/c/m, returning up to four CRT plaintext candidates on decrypt.' },
    encodeLabel: { zh: 'Encrypt m^2', en: 'Encrypt m^2' },
    decodeLabel: { zh: 'Decrypt c', en: 'Decrypt c' },
  },
  {
    id: 'rsa-helper',
    category: 'crypto',
    name: { zh: 'RSA CTF 辅助', en: 'RSA CTF Helper' },
    summary: { zh: '解析 n/e/c/p/q/phi 风格参数，并给出 RsaCtfTool、Sage 和 Python 命令模板。', en: 'Parses n/e/c/p/q/phi-style parameters and emits RsaCtfTool, Sage, and Python command templates.' },
    supportsEncode: false,
    decodeLabel: { zh: '生成辅助命令', en: 'Build helpers' },
  },
  {
    id: 'rsa-oaep',
    category: 'crypto',
    name: { zh: 'RSA-OAEP', en: 'RSA-OAEP' },
    summary: { zh: 'WebCrypto 原生 RSA-OAEP 加解密：解密需 n/e/d/p/q，hash 自动尝试 SHA-1/256/384/512；加密需 n/e。', en: 'Native WebCrypto RSA-OAEP: decryption needs n/e/d/p/q with auto hash probing; encryption needs n/e.' },
    params: [],
  },
  {
    id: 'coppersmith',
    category: 'crypto',
    name: { zh: 'Coppersmith 已知前缀', en: 'Coppersmith (Stereotyped)' },
    summary: { zh: '小指数 e 且明文前缀已知的还原：整数 e 次开方 + 短尾枚举。完整格基规约（LLL）未实现。', en: 'Stereotyped message recovery for small e: integer e-th root plus short-suffix enumeration. Full LLL-based Coppersmith not implemented.' },
    params: ['secret'],
  },
  {
    id: 'pgp-parse',
    category: 'crypto',
    name: { zh: 'PGP/GPG 结构解析', en: 'PGP Packet Parser' },
    summary: { zh: '只读解析 PGP/GPG 报文的 packet 结构（tag/算法/长度），不做任何解密。支持 ASCII armor 与二进制 hex。', en: 'Read-only RFC 4880 packet structure view (tag/algo/length); no decryption. Accepts ASCII armor or binary hex.' },
    params: [],
  },
  {
    id: 'cbc-padding-demo',
    category: 'crypto',
    name: { zh: 'CBC Padding Oracle 演示', en: 'CBC Padding Oracle Demo' },
    summary: { zh: '教学演示：本地模拟 padding oracle 逐字节还原与 bit-flip 注入（改 IV 翻转明文），全程无网络。可选 64-hex AES-256 密钥。', en: 'Local teaching demo: padding-oracle byte recovery and bit-flip injection via IV. Optional 64-hex AES-256 key. No network.' },
    params: ['secret'],
  },
  {
    id: 'signature-nonce-helper',
    category: 'crypto',
    name: { zh: '签名重复 nonce', en: 'Signature Nonce Reuse' },
    summary: { zh: '解析 ECDSA / DSA / Schnorr 的 r/s/z、DER 签名或 JOSE token，检测重复 nonce 并恢复 k 与私钥。', en: 'Parses ECDSA/DSA/Schnorr r/s/z values, DER signatures, or JOSE tokens, detects nonce reuse, and recovers k plus the private key.' },
    supportsEncode: false,
    decodeLabel: { zh: '分析签名', en: 'Analyze signatures' },
  },
  {
    id: 'discrete-log-helper',
    category: 'crypto',
    name: { zh: '离散对数 / ElGamal', en: 'Discrete Log / ElGamal' },
    summary: { zh: '解析 p/g/h/q 与可选 c1/c2，优先用 BSGS 和平滑阶 Pohlig-Hellman 恢复指数，并可顺带解 ElGamal。', en: 'Parses p/g/h/q with optional c1/c2, prefers BSGS and smooth-order Pohlig-Hellman to recover exponents, and can also decrypt ElGamal ciphertexts.' },
    supportsEncode: false,
    decodeLabel: { zh: '分析 DLP', en: 'Analyze DLP' },
  },
  {
    id: 'mt19937-helper',
    category: 'crypto',
    name: { zh: 'MT19937 状态恢复', en: 'MT19937 State Helper' },
    summary: { zh: '解析连续 32-bit 输出，判断能否克隆 Mersenne Twister 状态并预测后续值。', en: 'Parses consecutive 32-bit outputs to determine whether Mersenne Twister state cloning and next-value prediction are possible.' },
    supportsEncode: false,
    decodeLabel: { zh: '分析 MT19937', en: 'Analyze MT19937' },
  },
  {
    id: 'lcg-helper',
    category: 'crypto',
    name: { zh: 'LCG 参数恢复', en: 'LCG Parameter Helper' },
    summary: { zh: '根据连续输出和可选 modulus 推断或排查 LCG 的 a/c/m 参数。', en: 'Recovers or triages LCG a/c/m from consecutive outputs and optional modulus.' },
    supportsEncode: false,
    decodeLabel: { zh: '分析 LCG', en: 'Analyze LCG' },
    params: ['secret'],
  },
  {
    id: 'lfsr-helper',
    category: 'crypto',
    name: { zh: 'LFSR / Berlekamp-Massey', en: 'LFSR / Berlekamp-Massey' },
    summary: { zh: '对 bit keystream 运行 Berlekamp-Massey，估计线性复杂度并恢复反馈多项式。', en: 'Runs Berlekamp-Massey on bit keystreams to estimate linear complexity and feedback polynomial.' },
    supportsEncode: false,
    decodeLabel: { zh: '恢复 LFSR', en: 'Recover LFSR' },
  },
  {
    id: 'hash-length-extension-helper',
    category: 'crypto',
    name: { zh: 'Hash 长度扩展辅助', en: 'Hash Length-extension Helper' },
    summary: { zh: '识别 MD5/SHA1/SHA256 secret-prefix MAC 风险，并生成本地实验模板', en: 'Identifies MD5/SHA1/SHA256 secret-prefix MAC risk and builds local lab templates.' },
    supportsEncode: false,
    decodeLabel: { zh: '生成模板', en: 'Build template' },
    params: ['hashAlgorithm', 'secret', 'knownPlaintext'],
  },
  {
    id: 'crypto-attack-helper',
    category: 'crypto',
    name: { zh: 'CTF 密码攻击速查', en: 'CTF Crypto Attack Helper' },
    summary: { zh: '按题目材料生成 RSA、ECC、LCG、LFSR、LLL、长度扩展和 oracle 路径的工具链提示。', en: 'Builds toolchain hints for heavyweight RSA, ECC, LCG, LFSR, LLL, hash-extension, and oracle attacks.' },
    supportsEncode: false,
    decodeLabel: { zh: '生成速查', en: 'Build checklist' },
  },
  {
    id: 'frequency-analysis',
    category: 'crypto',
    name: { zh: '字母频率分析', en: 'Frequency Analysis' },
    summary: { zh: '统计字母、字符和 n-gram 频率，用于单表替换、Caesar、Vigenere 前置分析', en: 'Counts letters, characters, and n-grams for substitution, Caesar, and Vigenere triage.' },
    supportsEncode: false,
    decodeLabel: { zh: '分析频率', en: 'Analyze' },
  },
  {
    id: 'buddha',
    category: 'crypto',
    name: { zh: '与佛论禅', en: 'Buddha Says' },
    summary: { zh: 'keyfc 土豆码（佛曰/魔曰）：UTF-16 字节流经固定密钥 AES-256-CBC 后按 128 字佛表输出，中文 CTF 高频题，支持魔曰前缀的倒序变体。', en: 'keyfc potato code: UTF-16 bytes through fixed-key AES-256-CBC mapped onto a 128-char Buddha alphabet; also handles the reversed 魔曰 variant.' },
  },
  {
    id: 'buddha-v2',
    category: 'crypto',
    name: { zh: '如是我闻（佛曰 V2）', en: 'Thus Have I Heard' },
    summary: { zh: 'keyfc V2：256 字码表 + 同一固定密钥 AES，明文打包在 zip/7z 容器内。未压缩条目直接解出；LZMA 压缩条目给出容器 hex 供本地 7-Zip 接手。', en: 'keyfc V2: 256-char alphabet with the same fixed AES key over a zip/7z container. Stored entries decode inline; LZMA entries fall back to container hex.' },
    supportsEncode: false,
    decodeLabel: { zh: '参悟', en: 'Decode' },
  },
  {
    id: 'bear-says',
    category: 'crypto',
    name: { zh: '与熊论道（熊曰）', en: 'Bear Says' },
    summary: { zh: '熊曰编码：明文 raw deflate 压缩后做 basE91 数值编码，映射 91 字熊语字典并整体倒序，密文形如「熊曰：呋…」。', en: 'XiongYue: raw deflate, then basE91 digits mapped onto a 91-char bear dictionary and reversed; ciphertext starts with 熊曰：呋.' },
  },
  {
    id: 'baijiaxing',
    category: 'crypto',
    name: { zh: '百家姓编码', en: 'Hundred Family Surnames' },
    summary: { zh: '73 姓映射表：主流把 base64 字符替换为姓氏，也有明文直接替换的流派；解码先试 base64 再回退直接替换，双路自动兼容。', en: '73-surname table: mainstream variant replaces base64 characters, another replaces plaintext directly; decoding tries base64 first and falls back.' },
  },
  {
    id: 'hexagram',
    category: 'crypto',
    name: { zh: '六十四卦编码', en: 'I Ching Hexagrams' },
    summary: { zh: '六十四卦双流派：卦名流把 base64 字符映射为卦名（坤剥比观…），卦符流输出 Unicode 卦符（䷀-䷿）；解码按密文外观自动分流。', en: 'Two hexagram variants: name-based (base64 chars to 卦名) and Unicode symbols (䷀-䷿); decoding auto-detects the variant.' },
    params: ['variant'],
  },
  {
    id: 'sexagesimal',
    category: 'crypto',
    name: { zh: '天干地支编码', en: 'Sexagesimal Cycle' },
    summary: { zh: '六十甲子 base-60 大整数编码：字节流转大整数后按甲子到癸亥输出，每两位一组，chai2010 base60 流派。', en: 'Base-60 big-integer encoding over the 60 jiazi pairs (甲子…癸亥), two characters per digit, chai2010 base60 style.' },
  },
  {
    id: 'cloud-shadow',
    category: 'crypto',
    name: { zh: '云影密码', en: 'Cloud Shadow' },
    summary: { zh: '幂数加密（01248 密码）：0 作分隔，段内 1/2/4/8 求和映射 A-Z；解码唯一，编码按 8/4/2/1 贪心分解。', en: 'Power-number cipher: 0 separates segments, digits 1/2/4/8 sum to A-Z; decoding is unique, encoding greedily decomposes via 8/4/2/1.' },
  },
  {
    id: 'pizzini',
    category: 'crypto',
    name: { zh: 'Pizzini', en: 'Pizzini' },
    summary: { zh: '黑手党数字便签：字母序号 +3 拼接（A=4…Z=29），解码贪心自分隔，兼容 1-3→X/Y/Z 历史流派。', en: 'Mafia numeric notes: letter index +3 concatenated (A=4...Z=29); greedy self-delimiting decode with 1-3→X/Y/Z legacy fallback.' },
  },
  {
    id: 'cisco-type7',
    category: 'crypto',
    name: { zh: 'Cisco Type 7', en: 'Cisco Type 7' },
    summary: { zh: 'Cisco IOS 弱混淆密码：两位十进制种子 + 十六进制，与固定密钥表逐字节异或，可逆（编码固定种子 09）。', en: 'Cisco IOS weak obfuscation: 2-digit seed + hex, XORed byte-wise with a fixed key table; reversible (encoding uses seed 09).' },
  },
  {
    id: 'decabit',
    category: 'crypto',
    name: { zh: 'Decabit 脉冲码', en: 'Decabit' },
    summary: { zh: '电力线纹波控制脉冲码：每字符 10 个 +/- 脉冲（ASCII 映射，126=全 +），解码兼容 1/0 记法。', en: 'Ripple-control pulse code: 10 +/- pulses per ASCII character (126 = all +); decode accepts 1/0 notation.' },
  },
  {
    id: 'cetacean',
    category: 'crypto',
    name: { zh: 'Cetacean', en: 'Cetacean' },
    summary: { zh: 'CyberChef 鲸豚密码：字符 16bit 二进制，1→e、0→E，空格原样；解码兼容 A/B、1/0 变体。', en: 'CyberChef whale cipher: 16-bit binary per character, 1→e and 0→E, spaces kept; decode accepts A/B and 1/0 variants.' },
  },
  {
    id: 'albam',
    category: 'crypto',
    name: { zh: 'Albam', en: 'Albam' },
    summary: { zh: '希伯来 Temurah 半表互换：默认 A↔N（ROT13 同构、加解同表），可选 CacheSleuth +11 流派。', en: 'Hebrew Temurah half-table swap: default A↔N (ROT13-equivalent involution), optional CacheSleuth +11 variant.' },
    params: ['variant'],
  },
  {
    id: 'carbonaro',
    category: 'crypto',
    name: { zh: 'Carbonaro', en: 'Carbonaro' },
    summary: { zh: '烧炭党单表替换（对合表，含 H/J/K/Q/U/W/X/Y 共 8 个不动点），加解同表，非字母原样。', en: 'Carbonari monoalphabetic substitution (involution table with 8 fixed points H/J/K/Q/U/W/X/Y); same table both ways.' },
  },
  {
    id: 'brainfuck',
    category: 'text',
    name: { zh: 'Brainfuck 运行/编码', en: 'Brainfuck Run / Encode' },
    summary: { zh: '运行 Brainfuck 程序，或把文本生成为简单的 Brainfuck 输出程序。', en: 'Runs Brainfuck programs or emits simple Brainfuck text-output programs for CTF misc puzzles.' },
    encodeLabel: { zh: '生成 BF', en: 'Generate BF' },
    decodeLabel: { zh: '运行 BF', en: 'Run BF' },
    params: ['secret', 'iterations'],
  },
  {
    id: 'ook',
    category: 'text',
    name: { zh: 'Ook! / Brainfuck', en: 'Ook! / Brainfuck' },
    summary: { zh: '在 Brainfuck 指令与 Ook! token 之间互转，适合 esolang 题目。', en: 'Converts Brainfuck instructions to and from Ook! tokens for esolang CTF misc puzzles.' },
    encodeLabel: { zh: 'BF to Ook!', en: 'BF to Ook!' },
    decodeLabel: { zh: 'Ook! to BF', en: 'Ook! to BF' },
  },
  {
    id: 'jsfuck-helper',
    category: 'text',
    name: { zh: 'JSFuck 安全分析', en: 'JSFuck Safe Inspector' },
    summary: { zh: '安全检查 JSFuck / 纯符号 JavaScript 混淆，提取可见字符串和转义片段而不执行可疑代码。', en: 'Inspects JSFuck/symbol-only JavaScript obfuscation, extracting visible strings and escapes without executing suspicious code.' },
    supportsEncode: false,
    decodeLabel: { zh: '安全分析', en: 'Inspect safely' },
  },
  {
    id: 'jsfuck',
    category: 'text',
    name: { zh: 'JSFuck 还原', en: 'JSFuck' },
    summary: { zh: '静态求值还原 JSFuck 混淆为可读源码（全程不执行代码），也可把任意文本编码为 JSFuck。', en: 'Statically restores JSFuck obfuscation to readable source without executing code; can also encode text to JSFuck.' },
  },
  {
    id: 'aaencode',
    category: 'text',
    name: { zh: 'aaencode 还原', en: 'aaencode' },
    summary: { zh: '静态求值还原颜文字 aaencode 混淆（全程不执行代码），自动附带内嵌 atob 文本，也可编码。', en: 'Statically restores aaencode emoticon obfuscation without executing code, surfacing embedded atob text; can also encode.' },
  },
  {
    id: 'jjencode',
    category: 'text',
    name: { zh: 'jjencode 还原', en: 'jjencode' },
    summary: { zh: '静态求值还原 jjencode 符号混淆（全程不执行代码），自动附带内嵌 atob 文本，也可编码。', en: 'Statically restores jjencode symbol obfuscation without executing code, surfacing embedded atob text; can also encode.' },
  },
  {
    id: 'jwt',
    category: 'token',
    name: { zh: 'JWT 解析', en: 'JWT Parser' },
    summary: { zh: '解析 JWT 的 Header、Payload 和 Signature，并标出 `exp` / `iat` / `nbf` 时间字段。', en: 'Parses JWT header, payload, signature, and exp/iat/nbf timestamps.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 JWT', en: 'Parse JWT' },
  },
  {
    id: 'jwt-hmac',
    category: 'token',
    name: { zh: 'JWT HMAC 签名/验签', en: 'JWT HMAC Sign / Verify' },
    summary: { zh: '本地生成或校验 HS256 / HS384 / HS512 JWT，适合 token 题和课堂演示。', en: 'Creates or verifies HS256/HS384/HS512 JWTs locally for CTF token challenges and classroom demos.' },
    encodeLabel: { zh: '签名 JWT', en: 'Sign JWT' },
    decodeLabel: { zh: '验签 JWT', en: 'Verify JWT' },
    params: ['hashAlgorithm', 'secret'],
  },
  {
    id: 'jwt-public',
    category: 'token',
    name: { zh: 'JWT/JWS 公钥验签', en: 'JWT/JWS Public Verify' },
    summary: { zh: '使用 PEM、公钥证书、JWK 或 JWKS 验签 `RS256`、`PS256`、`ES256`、`EdDSA` 等 JWT / JWS。', en: 'Verifies RS256, PS256, ES256, EdDSA, and similar JWT/JWS signatures using PEM, certificates, JWK, or JWKS for CTF token challenges.' },
    supportsEncode: false,
    decodeLabel: { zh: '公钥验签', en: 'Verify with public key' },
    params: ['secret'],
  },
  {
    id: 'fernet',
    category: 'token',
    name: { zh: 'Fernet Token', en: 'Fernet Token' },
    summary: { zh: '解析和生成 Python cryptography Fernet token，包含时间戳、AES-128-CBC、HMAC-SHA256 校验与解密。', en: 'Parses and creates Python cryptography Fernet tokens with timestamp, AES-128-CBC, HMAC-SHA256 verification, and decryption.' },
    encodeLabel: { zh: '生成 token', en: 'Create token' },
    decodeLabel: { zh: '解析/解密', en: 'Parse / Decrypt' },
    params: ['secret'],
  },
  {
    id: 'hotp',
    category: 'token',
    name: { zh: 'HOTP', en: 'HOTP' },
    summary: { zh: '基于 Base32 secret、counter 和 HMAC 算法生成 HOTP，一次性验证码题里很常见。', en: 'Generates HOTP codes from a Base32 secret, counter, and HMAC algorithm for common OTP CTF challenges.' },
    encodeLabel: { zh: '生成 HOTP', en: 'Generate HOTP' },
    supportsDecode: false,
    params: ['secret', 'hashAlgorithm', 'digits', 'counter'],
  },
  {
    id: 'totp',
    category: 'token',
    name: { zh: 'TOTP', en: 'TOTP' },
    summary: { zh: '基于 Base32 secret、时间步长和时间戳生成 TOTP，适合 MFA / Authenticator 类题目。', en: 'Generates TOTP codes from a Base32 secret, time step, and timestamp for Google Authenticator or MFA-style challenges.' },
    encodeLabel: { zh: '生成 TOTP', en: 'Generate TOTP' },
    supportsDecode: false,
    params: ['secret', 'hashAlgorithm', 'digits', 'timeStep', 'otpTimestamp'],
  },
  {
    id: 'otpauth-uri',
    category: 'token',
    name: { zh: 'otpauth URI', en: 'otpauth URI' },
    summary: { zh: '解析或生成 otpauth:// URI，并用其中参数复算 HOTP / TOTP 验证码。', en: 'Parses or creates otpauth:// URIs and recalculates HOTP/TOTP codes from the embedded parameters.' },
    encodeLabel: { zh: '生成 URI', en: 'Create URI' },
    decodeLabel: { zh: '解析 URI', en: 'Parse URI' },
    params: ['variant', 'secret', 'hashAlgorithm', 'digits', 'timeStep', 'counter'],
  },
  {
    id: 'querystring',
    category: 'token',
    name: { zh: 'QueryString', en: 'QueryString' },
    summary: { zh: '在 URL 查询串与 JSON 对象之间互转，适合调试请求参数。', en: 'Converts URL query strings to and from JSON objects.' },
  },
  {
    id: 'basic-auth',
    category: 'token',
    name: { zh: 'Basic Auth', en: 'Basic Auth' },
    summary: { zh: '在 `username:password` 与 HTTP Basic `Authorization` 头之间互转。', en: 'Converts username:password to and from HTTP Basic Authorization headers.' },
  },
  {
    id: 'punycode',
    category: 'token',
    name: { zh: 'Punycode / IDN', en: 'Punycode / IDN' },
    summary: { zh: '在 Unicode 域名与 xn-- Punycode 标签之间互转。', en: 'Converts Unicode hostnames to and from xn-- Punycode labels.' },
  },
  {
    id: 'pem-block',
    category: 'token',
    name: { zh: 'PEM 封装', en: 'PEM Block' },
    summary: { zh: '在原始 Base64 材料与 PEM 头尾块之间互转，适合证书、公钥和私钥片段整理。', en: 'Converts between raw Base64 material and PEM header/footer blocks for certs and keys.' },
    params: ['blockLabel'],
  },
  {
    id: 'asn1-der',
    category: 'token',
    name: { zh: 'ASN.1 DER/BER 树', en: 'ASN.1 DER/BER Tree' },
    summary: { zh: '把 PEM、Base64 或 Hex 形式的 DER/BER 数据解析成 TLV 树，适合证书、公钥和签名结构分析。', en: 'Parses DER/BER data from PEM, Base64, or Hex into a TLV tree for certificates, public keys, signatures, and crypto containers.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 ASN.1', en: 'Parse ASN.1' },
  },
  {
    id: 'jwk-jwe',
    category: 'token',
    name: { zh: 'JWK / JWE 解析', en: 'JWK / JWE Parser' },
    summary: { zh: '解析 JWK、JWKS 和 compact JWE 结构，展开 Base64URL 字段、密钥尺寸和 protected header。', en: 'Parses JWK, JWKS, and compact JWE structures, expanding Base64URL fields, key sizes, and protected headers.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 JOSE', en: 'Parse JOSE' },
  },
  {
    id: 'ssh-public-key',
    category: 'token',
    name: { zh: 'OpenSSH 公钥解析', en: 'OpenSSH Public Key Parser' },
    summary: { zh: '解析 ssh-rsa、ssh-ed25519、ecdsa-* 等 OpenSSH 公钥 blob，输出字段、位数和 SHA256 指纹。', en: 'Parses ssh-rsa, ssh-ed25519, ecdsa-* and related OpenSSH public key blobs with fields, sizes, and SHA256 fingerprint.' },
    supportsEncode: false,
    decodeLabel: { zh: '解析 SSH Key', en: 'Parse SSH key' },
  },
  {
    id: 'gzip',
    category: 'compress',
    name: { zh: 'GZip', en: 'GZip' },
    summary: { zh: '把文本压缩成 Base64 GZip，或把 Base64 GZip 解压成文本。', en: 'Compresses text to Base64 GZip or decompresses Base64 GZip.' },
    encodeLabel: { zh: '压缩', en: 'Compress' },
    decodeLabel: { zh: '解压', en: 'Decompress' },
  },
  {
    id: 'deflate',
    category: 'compress',
    name: { zh: 'Deflate', en: 'Deflate' },
    summary: { zh: '把文本压缩成 Base64 Deflate，或把 Base64 Deflate 解压成文本。', en: 'Compresses text to Base64 Deflate or decompresses Base64 Deflate.' },
    encodeLabel: { zh: '压缩', en: 'Compress' },
    decodeLabel: { zh: '解压', en: 'Decompress' },
  },
  {
    id: 'data-url',
    category: 'compress',
    name: { zh: 'Data URL', en: 'Data URL' },
    summary: { zh: '在文本与 data:mime;base64,... 封装之间互转。', en: 'Converts text to and from data:mime;base64,... wrappers.' },
    params: ['mimeType'],
  },
];

export const defaultParams: Record<ParamKey, string> = {
  variant: 'special',
  hashAlgorithm: 'sha256',
  secret: '',
  iv: '',
  keyword2: '',
  associatedData: '',
  hrp: 'bc',
  versionHex: '00',
  digits: '6',
  counter: '0',
  timeStep: '30',
  otpTimestamp: '',
  period: '5',
  iterations: '120000',
  shift: '13',
  separator: 'space',
  mimeType: 'text/plain;charset=utf-8',
  blockLabel: 'PUBLIC KEY',
  affineA: '5',
  affineB: '8',
  rails: '3',
  knownPlaintext: 'flag{',
  dropBytes: '768',
};
