export type Direction = 'encode' | 'decode';
export type CategoryId = 'smart' | 'web' | 'binary' | 'crypto' | 'text' | 'token' | 'compress';
export type OperationId =
  | 'smart-decode'
  | 'url-component'
  | 'url-form'
  | 'html-entity'
  | 'xml-entity'
  | 'unicode-escape'
  | 'utf7'
  | 'js-string'
  | 'c-string'
  | 'json-string'
  | 'unix-time'
  | 'base64'
  | 'base64url'
  | 'base32'
  | 'base45'
  | 'base58'
  | 'base58check'
  | 'bech32'
  | 'base62'
  | 'base36'
  | 'base91'
  | 'ascii85'
  | 'uuencode'
  | 'xxencode'
  | 'z-base-32'
  | 'base32768'
  | 'hex'
  | 'binary'
  | 'octal-codes'
  | 'ascii-codes'
  | 'a1z26'
  | 'morse'
  | 'nato-phonetic'
  | 'baudot'
  | 'bcd'
  | 'gray-code'
  | 'dna-code'
  | 'gsm7'
  | 'sms-pdu'
  | 'cbor'
  | 'messagepack'
  | 'protobuf-raw'
  | 'bson'
  | 'yenc'
  | 'bubble-babble'
  | 'quoted-printable'
  | 'utf16-bytes'
  | 'reverse-text'
  | 'keyboard-shift'
  | 'zero-width'
  | 'hash'
  | 'hash-identify'
  | 'hmac'
  | 'aes-gcm'
  | 'aes-cbc'
  | 'aes-ctr'
  | 'openssl-aes-256-cbc'
  | 'aes-cbc-raw'
  | 'aes-ctr-raw'
  | 'aes-ofb'
  | 'aes-gcm-siv'
  | 'aes-siv'
  | 'aes-ecb'
  | 'aes-cfb'
  | 'aes-kw'
  | 'aes-kwp'
  | 'aes-cmac'
  | 'des'
  | 'triple-des'
  | 'blowfish'
  | 'rabbit'
  | 'chacha20-orig'
  | 'chacha20'
  | 'xchacha20'
  | 'chacha20-poly1305'
  | 'xchacha20-poly1305'
  | 'salsa20'
  | 'xsalsa20'
  | 'xsalsa20-poly1305'
  | 'sm4'
  | 'rc4'
  | 'rc4-drop'
  | 'tea'
  | 'xtea'
  | 'xxtea'
  | 'bip39-seed'
  | 'vigenere'
  | 'beaufort'
  | 'autokey'
  | 'atbash'
  | 'bacon'
  | 'polybius'
  | 'tap-code'
  | 'playfair'
  | 'hill2'
  | 'substitution'
  | 'affine'
  | 'rail-fence'
  | 'scytale'
  | 'columnar'
  | 'porta'
  | 'gronsfeld'
  | 'bifid'
  | 'trifid'
  | 'four-square'
  | 'nihilist'
  | 'adfgx'
  | 'adfgvx'
  | 'xor'
  | 'xor-bruteforce'
  | 'xor-known-plaintext'
  | 'magic-xor-helper'
  | 'rot'
  | 'rot-bruteforce'
  | 'rot8000'
  | 'enigma'
  | 'rsa-raw'
  | 'rabin-raw'
  | 'rsa-helper'
  | 'rsa-oaep'
  | 'coppersmith'
  | 'pgp-parse'
  | 'cbc-padding-demo'
  | 'signature-nonce-helper'
  | 'discrete-log-helper'
  | 'mt19937-helper'
  | 'lcg-helper'
  | 'lfsr-helper'
  | 'hash-length-extension-helper'
  | 'crypto-attack-helper'
  | 'frequency-analysis'
  | 'brainfuck'
  | 'ook'
  | 'jsfuck-helper'
  | 'jsfuck'
  | 'aaencode'
  | 'jjencode'
  | 'jwt'
  | 'jwt-hmac'
  | 'jwt-public'
  | 'fernet'
  | 'hotp'
  | 'totp'
  | 'otpauth-uri'
  | 'querystring'
  | 'basic-auth'
  | 'punycode'
  | 'pem-block'
  | 'asn1-der'
  | 'jwk-jwe'
  | 'ssh-public-key'
  | 'gzip'
  | 'deflate'
  | 'data-url'
  | 'buddha'
  | 'buddha-v2'
  | 'bear-says'
  | 'baijiaxing'
  | 'hexagram'
  | 'sexagesimal'
  | 'cloud-shadow'
  | 'pizzini'
  | 'cisco-type7'
  | 'decabit'
  | 'cetacean'
  | 'albam'
  | 'carbonaro';

export type ParamKey = 'variant' | 'hashAlgorithm' | 'secret' | 'iv' | 'keyword2' | 'associatedData' | 'hrp' | 'versionHex' | 'digits' | 'counter' | 'timeStep' | 'otpTimestamp' | 'period' | 'iterations' | 'shift' | 'separator' | 'mimeType' | 'blockLabel' | 'affineA' | 'affineB' | 'rails' | 'knownPlaintext' | 'dropBytes';

export interface Operation {
  id: OperationId;
  category: CategoryId;
  name: { zh: string; en: string };
  summary: { zh: string; en: string };
  encodeLabel?: { zh: string; en: string };
  decodeLabel?: { zh: string; en: string };
  supportsEncode?: boolean;
  supportsDecode?: boolean;
  params?: ParamKey[];
}

export interface Detection {
  id: OperationId;
  label: string;
}

export const categories: Array<{ id: CategoryId; name: { zh: string; en: string }; note: { zh: string; en: string } }> = [
  { id: 'smart', name: { zh: '智能识别', en: 'Smart' }, note: { zh: '自动识别多层编码', en: 'Detect nested encodings' } },
  { id: 'web', name: { zh: 'Web 编码', en: 'Web' }, note: { zh: 'URL、HTML、Unicode、JS', en: 'URL, HTML, Unicode, JS' } },
  { id: 'binary', name: { zh: '进制与文本', en: 'Binary' }, note: { zh: 'Base 系列、Hex 与进制转换', en: 'Base families, Hex, radix' } },
  { id: 'crypto', name: { zh: '加密与摘要', en: 'Crypto' }, note: { zh: 'Hash、HMAC、AES、XOR', en: 'Hash, HMAC, AES, XOR' } },
  { id: 'text', name: { zh: '文本处理', en: 'Text' }, note: { zh: 'JSON 字符串与转义', en: 'JSON strings and escaping' } },
  { id: 'token', name: { zh: '令牌与协议', en: 'Tokens' }, note: { zh: 'JWT、Query、Basic Auth', en: 'JWT, Query, Basic Auth' } },
  { id: 'compress', name: { zh: '压缩封装', en: 'Compress' }, note: { zh: 'GZip、Deflate、Data URL', en: 'GZip, Deflate, Data URL' } },
];
